### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by mattirizarry** [mattirizarry/CS360-Project#7]
- [ ] #4 System Boundaries
- [ ] #5 UML Class Diagarms
- [ ] #6 UML Use Cases
- [ ] #9 UML Sequence Diagrams
- [ ] #10 UML State Diagrams
- [ ] #11 UML Component Diagrams
- [ ] #12 UML Deployment Diagram
- [ ] #13 UML Use Case Scenarios
